### ISSUE TITLE
How to perform inverse transformation?

### ISSUE THREAD

**Issue by vedanth-subramaniam** [lschmiddey/deep_tabular_augmentation#1]
After augmenting data how do you perform inverse transformation using mlprepare? I want to retain the original data and not the encoded values

**Comment by lschmiddey** [comment]
Are you talking about the cat_transform part? Next to the transformed dataframe this function will also give you two lists, containing the disctionaries for the transformed variables. You can use them via map for example to inverse the transformation.

**Comment by vedanth-subramaniam** [comment]
Yeah I saw that but then there is no function in mlprepare to perform inverse transformation? How do I use the dict then?

**Comment by lschmiddey** [comment]
I will add that as a function. Basically it's something like this: df['col1'].map(dict)

**Comment by vedanth-subramaniam** [comment]
But that might not work if the data which the autoencoder generates is not part of the map.

**Comment by lschmiddey** [comment]
You mean something like the 'amount' column like here: https://github.com/lschmiddey/deep_tabular_augmentation/blob/main/deep_data_augmentation.ipynb?
