### ISSUE TITLE
'deep_tabular_augmentation' has no attribute 'AutoencoderModel'

### ISSUE THREAD

**Issue by WiemHAD** [lschmiddey/deep_tabular_augmentation#7]
Hi, 
I'm using dta, but I get this error: 
module 'deep_tabular_augmentation' has no attribute 'AutoencoderModel'
I'm a beginner in data science, so I can't fix it by my self.  Any help, please ?

**Comment by lschmiddey** [comment]
Hi WiemHAD,

I'm not 100% sure you are referring to, but I think you might be using an old version. I think maybe this blogpost here: https://medium.com/analytics-vidhya/comparison-randomforest-with-oversampling-vs-augmented-data-bd7fcb96ef0f
might help you in how to use the DeepAugmenter.

When building the model you need to do something like this:

model = dta.Autoencoder(nn.Sequential(*dta.get_lin_layers(D_in, [50, 12, 12])),
                     nn.Sequential(*dta.get_lin_layers_rev(D_in, [50, 12, 12])),
                     latent_dim=5).to(device)

**Comment by Taichi-Pink** [comment]
Hi @lschmiddey,

I guess @WiemHAD referred to the function **AutoencoderModel** in this postblog:[postblog](https://github.com/lschmiddey/fastpages_/blob/master/_notebooks/2021-04-10-DeepLearning_TabularDataAugmentation.ipynb).
