### ISSUE TITLE
Does dta works with multi-label data or continious target variable?

### ISSUE THREAD

**Issue by Dimot322** [lschmiddey/deep_tabular_augmentation#8]
Hi, does dta supports non-binary target input?  
In my case I am trying to generate continuous features (which is my future target for regression purposes) of multi-label dataset.
The _run.recorder.plot()_ gives me this.
![image](https://user-images.githubusercontent.com/52868590/163285972-b57f6bf7-5333-42c4-b956-9707b54145e4.png)

**Comment by lschmiddey** [comment]
dta supports continuous data as input variables: https://lschmiddey.github.io/fastpages_/2021/11/07/DeepLearning_TabularDataAugmentation_Refactored.html
The variables in that case are continuous. Or did I missunderstand understand your question?

**Comment by Dimot322** [comment]
> dta supports continuous data as input variables: https://lschmiddey.github.io/fastpages_/2021/11/07/DeepLearning_TabularDataAugmentation_Refactored.html The variables in that case are continuous. Or did I missunderstand understand your question?

Thanks for your reply!
Yes, the variables are continious, but the target is binary. In that case we need to specify target_name and target_class for Loader class. So i want to give continious or binary class (which leads to result in my attachement). My question is how i can specify target_class with continious variable.

**Comment by lschmiddey** [comment]
Good question, I did build the dta for binary/categorical variables and havent thought about this. I will have a look whether I can update dta to also include continuous target variables

**Comment by lschmiddey** [comment]
Ahoi Dimot322,
I updated the package, so one can now also use it in cases when there is no target per se required/wanted. You can install the package like so: pip install deep-tabular-augmentation
The latest version under which this feature is available is 0.5.0
Also I attached a notebook file where you can see this in action: https://github.com/lschmiddey/deep_tabular_augmentation/blob/main/Notebooks/DeepLearning_DataAugmentation_RF_2.ipynb
I hope this helps :)

**Comment by lschmiddey** [comment]
also, this might help: https://lasse-schmidt90.medium.com/deep-tabular-augmentation-for-regression-tasks-81c1dfdb41d4

**Comment by Dimot322** [comment]
Thanks, it helps a lot!


> Ahoi Dimot322, I updated the package, so one can now also use it in cases when there is no target per se required/wanted. You can install the package like so: pip install deep-tabular-augmentation The latest version under which this feature is available is 0.5.0 Also I attached a notebook file where you can see this in action: https://github.com/lschmiddey/deep_tabular_augmentation/blob/main/Notebooks/DeepLearning_DataAugmentation_RF_2.ipynb I hope this helps :)
